/** Generated by YAKINDU Statechart Tools code generator. */
package drinkingfactory.drinkingfactory;

import drinkingfactory.ITimer;
import java.util.LinkedList;
import java.util.List;

public class DrinkingfactoryStatemachine implements IDrinkingfactoryStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private List<SCInterfaceListener> listeners = new LinkedList<SCInterfaceListener>();
		
		public List<SCInterfaceListener> getListeners() {
			return listeners;
		}
		private boolean addMoney;
		
		
		public void raiseAddMoney() {
			synchronized(DrinkingfactoryStatemachine.this) {
				addMoney = true;
			}
		}
		
		private boolean paying;
		
		
		public void raisePaying() {
			synchronized(DrinkingfactoryStatemachine.this) {
				paying = true;
			}
		}
		
		private boolean paymentValidate;
		
		
		public void raisePaymentValidate() {
			synchronized(DrinkingfactoryStatemachine.this) {
				paymentValidate = true;
			}
		}
		
		private boolean resetMachine;
		
		
		public void raiseResetMachine() {
			synchronized(DrinkingfactoryStatemachine.this) {
				resetMachine = true;
			}
		}
		
		private boolean userAction;
		
		
		public void raiseUserAction() {
			synchronized(DrinkingfactoryStatemachine.this) {
				userAction = true;
			}
		}
		
		private boolean cupGrabbed;
		
		
		public void raiseCupGrabbed() {
			synchronized(DrinkingfactoryStatemachine.this) {
				cupGrabbed = true;
			}
		}
		
		private boolean tempReached;
		
		
		public void raiseTempReached() {
			synchronized(DrinkingfactoryStatemachine.this) {
				tempReached = true;
			}
		}
		
		private boolean cupFilled;
		
		
		public void raiseCupFilled() {
			synchronized(DrinkingfactoryStatemachine.this) {
				cupFilled = true;
			}
		}
		
		private boolean coffeeSelected;
		
		
		public void raiseCoffeeSelected() {
			synchronized(DrinkingfactoryStatemachine.this) {
				coffeeSelected = true;
			}
		}
		
		private boolean teaSelected;
		
		
		public void raiseTeaSelected() {
			synchronized(DrinkingfactoryStatemachine.this) {
				teaSelected = true;
			}
		}
		
		private boolean espressoSelected;
		
		
		public void raiseEspressoSelected() {
			synchronized(DrinkingfactoryStatemachine.this) {
				espressoSelected = true;
			}
		}
		
		private boolean soupSelected;
		
		
		public void raiseSoupSelected() {
			synchronized(DrinkingfactoryStatemachine.this) {
				soupSelected = true;
			}
		}
		
		private boolean icedTeaSelected;
		
		
		public void raiseIcedTeaSelected() {
			synchronized(DrinkingfactoryStatemachine.this) {
				icedTeaSelected = true;
			}
		}
		
		private boolean doResetMoney;
		
		
		public boolean isRaisedDoResetMoney() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return doResetMoney;
			}
		}
		
		protected void raiseDoResetMoney() {
			synchronized(DrinkingfactoryStatemachine.this) {
				doResetMoney = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoResetMoneyRaised();
				}
			}
		}
		
		private boolean doResetMachine;
		
		
		public boolean isRaisedDoResetMachine() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return doResetMachine;
			}
		}
		
		protected void raiseDoResetMachine() {
			synchronized(DrinkingfactoryStatemachine.this) {
				doResetMachine = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoResetMachineRaised();
				}
			}
		}
		
		private boolean doCleaning;
		
		
		public boolean isRaisedDoCleaning() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return doCleaning;
			}
		}
		
		protected void raiseDoCleaning() {
			synchronized(DrinkingfactoryStatemachine.this) {
				doCleaning = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDoCleaningRaised();
				}
			}
		}
		
		private boolean grindBeans;
		
		
		public boolean isRaisedGrindBeans() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return grindBeans;
			}
		}
		
		protected void raiseGrindBeans() {
			synchronized(DrinkingfactoryStatemachine.this) {
				grindBeans = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onGrindBeansRaised();
				}
			}
		}
		
		private boolean takeTeaBag;
		
		
		public boolean isRaisedTakeTeaBag() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return takeTeaBag;
			}
		}
		
		protected void raiseTakeTeaBag() {
			synchronized(DrinkingfactoryStatemachine.this) {
				takeTeaBag = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onTakeTeaBagRaised();
				}
			}
		}
		
		private boolean takeOffTeaBag;
		
		
		public boolean isRaisedTakeOffTeaBag() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return takeOffTeaBag;
			}
		}
		
		protected void raiseTakeOffTeaBag() {
			synchronized(DrinkingfactoryStatemachine.this) {
				takeOffTeaBag = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onTakeOffTeaBagRaised();
				}
			}
		}
		
		private boolean takeCoffeePod;
		
		
		public boolean isRaisedTakeCoffeePod() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return takeCoffeePod;
			}
		}
		
		protected void raiseTakeCoffeePod() {
			synchronized(DrinkingfactoryStatemachine.this) {
				takeCoffeePod = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onTakeCoffeePodRaised();
				}
			}
		}
		
		private boolean heatWater;
		
		
		public boolean isRaisedHeatWater() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return heatWater;
			}
		}
		
		protected void raiseHeatWater() {
			synchronized(DrinkingfactoryStatemachine.this) {
				heatWater = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onHeatWaterRaised();
				}
			}
		}
		
		private boolean putCup;
		
		
		public boolean isRaisedPutCup() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return putCup;
			}
		}
		
		protected void raisePutCup() {
			synchronized(DrinkingfactoryStatemachine.this) {
				putCup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPutCupRaised();
				}
			}
		}
		
		private boolean addSugar;
		
		
		public boolean isRaisedAddSugar() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return addSugar;
			}
		}
		
		protected void raiseAddSugar() {
			synchronized(DrinkingfactoryStatemachine.this) {
				addSugar = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onAddSugarRaised();
				}
			}
		}
		
		private boolean pourWater;
		
		
		public boolean isRaisedPourWater() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return pourWater;
			}
		}
		
		protected void raisePourWater() {
			synchronized(DrinkingfactoryStatemachine.this) {
				pourWater = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPourWaterRaised();
				}
			}
		}
		
		private boolean putBeans;
		
		
		public boolean isRaisedPutBeans() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return putBeans;
			}
		}
		
		protected void raisePutBeans() {
			synchronized(DrinkingfactoryStatemachine.this) {
				putBeans = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPutBeansRaised();
				}
			}
		}
		
		private boolean checkPayment;
		
		
		public boolean isRaisedCheckPayment() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return checkPayment;
			}
		}
		
		protected void raiseCheckPayment() {
			synchronized(DrinkingfactoryStatemachine.this) {
				checkPayment = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCheckPaymentRaised();
				}
			}
		}
		
		private boolean checkStocks;
		
		
		public boolean isRaisedCheckStocks() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return checkStocks;
			}
		}
		
		protected void raiseCheckStocks() {
			synchronized(DrinkingfactoryStatemachine.this) {
				checkStocks = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onCheckStocksRaised();
				}
			}
		}
		
		private boolean displayOptions;
		
		
		public boolean isRaisedDisplayOptions() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return displayOptions;
			}
		}
		
		protected void raiseDisplayOptions() {
			synchronized(DrinkingfactoryStatemachine.this) {
				displayOptions = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onDisplayOptionsRaised();
				}
			}
		}
		
		private boolean pourMilk;
		
		
		public boolean isRaisedPourMilk() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return pourMilk;
			}
		}
		
		protected void raisePourMilk() {
			synchronized(DrinkingfactoryStatemachine.this) {
				pourMilk = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPourMilkRaised();
				}
			}
		}
		
		private boolean pourSyrup;
		
		
		public boolean isRaisedPourSyrup() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return pourSyrup;
			}
		}
		
		protected void raisePourSyrup() {
			synchronized(DrinkingfactoryStatemachine.this) {
				pourSyrup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPourSyrupRaised();
				}
			}
		}
		
		private boolean addBread;
		
		
		public boolean isRaisedAddBread() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return addBread;
			}
		}
		
		protected void raiseAddBread() {
			synchronized(DrinkingfactoryStatemachine.this) {
				addBread = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onAddBreadRaised();
				}
			}
		}
		
		private boolean addIceCream;
		
		
		public boolean isRaisedAddIceCream() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return addIceCream;
			}
		}
		
		protected void raiseAddIceCream() {
			synchronized(DrinkingfactoryStatemachine.this) {
				addIceCream = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onAddIceCreamRaised();
				}
			}
		}
		
		private boolean pourSoup;
		
		
		public boolean isRaisedPourSoup() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return pourSoup;
			}
		}
		
		protected void raisePourSoup() {
			synchronized(DrinkingfactoryStatemachine.this) {
				pourSoup = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPourSoupRaised();
				}
			}
		}
		
		private boolean putSpice;
		
		
		public boolean isRaisedPutSpice() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return putSpice;
			}
		}
		
		protected void raisePutSpice() {
			synchronized(DrinkingfactoryStatemachine.this) {
				putSpice = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onPutSpiceRaised();
				}
			}
		}
		
		private boolean lockDoor;
		
		
		public boolean isRaisedLockDoor() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return lockDoor;
			}
		}
		
		protected void raiseLockDoor() {
			synchronized(DrinkingfactoryStatemachine.this) {
				lockDoor = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onLockDoorRaised();
				}
			}
		}
		
		private boolean unlockDoor;
		
		
		public boolean isRaisedUnlockDoor() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return unlockDoor;
			}
		}
		
		protected void raiseUnlockDoor() {
			synchronized(DrinkingfactoryStatemachine.this) {
				unlockDoor = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onUnlockDoorRaised();
				}
			}
		}
		
		private boolean nitrogenInjection;
		
		
		public boolean isRaisedNitrogenInjection() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return nitrogenInjection;
			}
		}
		
		protected void raiseNitrogenInjection() {
			synchronized(DrinkingfactoryStatemachine.this) {
				nitrogenInjection = true;
				for (SCInterfaceListener listener : listeners) {
					listener.onNitrogenInjectionRaised();
				}
			}
		}
		
		private String drinkName;
		
		public synchronized String getDrinkName() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return drinkName;
			}
		}
		
		public void setDrinkName(String value) {
			synchronized(DrinkingfactoryStatemachine.this) {
				this.drinkName = value;
			}
		}
		
		private String drinkSize;
		
		public synchronized String getDrinkSize() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return drinkSize;
			}
		}
		
		public void setDrinkSize(String value) {
			synchronized(DrinkingfactoryStatemachine.this) {
				this.drinkSize = value;
			}
		}
		
		private boolean optionDrink;
		
		public synchronized boolean getOptionDrink() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return optionDrink;
			}
		}
		
		public void setOptionDrink(boolean value) {
			synchronized(DrinkingfactoryStatemachine.this) {
				this.optionDrink = value;
			}
		}
		
		private boolean optionSugar;
		
		public synchronized boolean getOptionSugar() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return optionSugar;
			}
		}
		
		public void setOptionSugar(boolean value) {
			synchronized(DrinkingfactoryStatemachine.this) {
				this.optionSugar = value;
			}
		}
		
		private boolean optionIceCream;
		
		public synchronized boolean getOptionIceCream() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return optionIceCream;
			}
		}
		
		public void setOptionIceCream(boolean value) {
			synchronized(DrinkingfactoryStatemachine.this) {
				this.optionIceCream = value;
			}
		}
		
		private long progress;
		
		public synchronized long getProgress() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return progress;
			}
		}
		
		public void setProgress(long value) {
			synchronized(DrinkingfactoryStatemachine.this) {
				this.progress = value;
			}
		}
		
		private boolean cupPlaced;
		
		public synchronized boolean getCupPlaced() {
			synchronized(DrinkingfactoryStatemachine.this) {
				return cupPlaced;
			}
		}
		
		public void setCupPlaced(boolean value) {
			synchronized(DrinkingfactoryStatemachine.this) {
				this.cupPlaced = value;
			}
		}
		
		protected void clearEvents() {
			addMoney = false;
			paying = false;
			paymentValidate = false;
			resetMachine = false;
			userAction = false;
			cupGrabbed = false;
			tempReached = false;
			cupFilled = false;
			coffeeSelected = false;
			teaSelected = false;
			espressoSelected = false;
			soupSelected = false;
			icedTeaSelected = false;
		}
		protected void clearOutEvents() {
		
		doResetMoney = false;
		doResetMachine = false;
		doCleaning = false;
		grindBeans = false;
		takeTeaBag = false;
		takeOffTeaBag = false;
		takeCoffeePod = false;
		heatWater = false;
		putCup = false;
		addSugar = false;
		pourWater = false;
		putBeans = false;
		checkPayment = false;
		checkStocks = false;
		displayOptions = false;
		pourMilk = false;
		pourSyrup = false;
		addBread = false;
		addIceCream = false;
		pourSoup = false;
		putSpice = false;
		lockDoor = false;
		unlockDoor = false;
		nitrogenInjection = false;
		}
		
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		payment_management_Payment,
		drink_management_configuration,
		activity_management_configuration,
		machine_management_Standby,
		machine_management_Cleaning,
		machine_management_checkingPayment,
		machine_management_Preparation,
		machine_management_Preparation_r1_step1,
		machine_management_Preparation_r1_step1_r1_Expresso,
		machine_management_Preparation_r1_step1_r1_sync,
		machine_management_Preparation_r1_step1_r2_General,
		machine_management_Preparation_r1_step1_r2_sync,
		machine_management_Preparation_r1_step2,
		machine_management_Preparation_r1_step2_r1_sync,
		machine_management_Preparation_r1_step2_r2_General,
		machine_management_Preparation_r1_step3,
		machine_management_Preparation_r1_step3_r1_Tea1,
		machine_management_Preparation_r1_step3_r1_sync,
		machine_management_Preparation_r1_step3_r1_tea2_small,
		machine_management_Preparation_r1_step3_r1_tea2_medium,
		machine_management_Preparation_r1_step3_r1_tea2_big,
		machine_management_Preparation_r1_step3_r1_soup_option,
		machine_management_Preparation_r1_step3_r2_General,
		machine_management_Preparation_r1_step3_r2_sync,
		machine_management_Preparation_r1_step3_r2_option,
		machine_management_Preparation_r1_step4,
		machine_management_Preparation_r1_step4_r1_cooling1,
		machine_management_Preparation_r1_step4_r1_sync,
		$NullState$
	};
	
	private final State[] stateVector = new State[5];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[7];
	
	private boolean resetMachineInternal;
	private boolean userActionInternal;
	private boolean drinkSelected;
	public DrinkingfactoryStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public synchronized void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		for (int i = 0; i < 5; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setDrinkName("");
		
		sCInterface.setDrinkSize("");
		
		sCInterface.setOptionDrink(false);
		
		sCInterface.setOptionSugar(false);
		
		sCInterface.setOptionIceCream(false);
		
		sCInterface.setProgress(0);
		
		sCInterface.setCupPlaced(false);
	}
	
	public synchronized void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_payment_management_default();
		enterSequence_drink_management_default();
		enterSequence_activity_management_default();
		enterSequence_machine_management_default();
	}
	
	public synchronized void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case payment_management_Payment:
				payment_management_Payment_react(true);
				break;
			case drink_management_configuration:
				drink_management_configuration_react(true);
				break;
			case activity_management_configuration:
				activity_management_configuration_react(true);
				break;
			case machine_management_Standby:
				machine_management_Standby_react(true);
				break;
			case machine_management_Cleaning:
				machine_management_Cleaning_react(true);
				break;
			case machine_management_checkingPayment:
				machine_management_checkingPayment_react(true);
				break;
			case machine_management_Preparation_r1_step1_r1_Expresso:
				machine_management_Preparation_r1_step1_r1_Expresso_react(true);
				break;
			case machine_management_Preparation_r1_step1_r1_sync:
				machine_management_Preparation_r1_step1_r1_sync_react(true);
				break;
			case machine_management_Preparation_r1_step1_r2_General:
				machine_management_Preparation_r1_step1_r2_General_react(true);
				break;
			case machine_management_Preparation_r1_step1_r2_sync:
				machine_management_Preparation_r1_step1_r2_sync_react(true);
				break;
			case machine_management_Preparation_r1_step2_r1_sync:
				machine_management_Preparation_r1_step2_r1_sync_react(true);
				break;
			case machine_management_Preparation_r1_step2_r2_General:
				machine_management_Preparation_r1_step2_r2_General_react(true);
				break;
			case machine_management_Preparation_r1_step3_r1_Tea1:
				machine_management_Preparation_r1_step3_r1_Tea1_react(true);
				break;
			case machine_management_Preparation_r1_step3_r1_sync:
				machine_management_Preparation_r1_step3_r1_sync_react(true);
				break;
			case machine_management_Preparation_r1_step3_r1_tea2_small:
				machine_management_Preparation_r1_step3_r1_tea2_small_react(true);
				break;
			case machine_management_Preparation_r1_step3_r1_tea2_medium:
				machine_management_Preparation_r1_step3_r1_tea2_medium_react(true);
				break;
			case machine_management_Preparation_r1_step3_r1_tea2_big:
				machine_management_Preparation_r1_step3_r1_tea2_big_react(true);
				break;
			case machine_management_Preparation_r1_step3_r1_soup_option:
				machine_management_Preparation_r1_step3_r1_soup_option_react(true);
				break;
			case machine_management_Preparation_r1_step3_r2_General:
				machine_management_Preparation_r1_step3_r2_General_react(true);
				break;
			case machine_management_Preparation_r1_step3_r2_sync:
				machine_management_Preparation_r1_step3_r2_sync_react(true);
				break;
			case machine_management_Preparation_r1_step3_r2_option:
				machine_management_Preparation_r1_step3_r2_option_react(true);
				break;
			case machine_management_Preparation_r1_step4_r1_cooling1:
				machine_management_Preparation_r1_step4_r1_cooling1_react(true);
				break;
			case machine_management_Preparation_r1_step4_r1_sync:
				machine_management_Preparation_r1_step4_r1_sync_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public synchronized void exit() {
		exitSequence_payment_management();
		exitSequence_drink_management();
		exitSequence_activity_management();
		exitSequence_machine_management();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public synchronized boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$||stateVector[2] != State.$NullState$||stateVector[3] != State.$NullState$||stateVector[4] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public synchronized boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		resetMachineInternal = false;
		userActionInternal = false;
		drinkSelected = false;
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
		sCInterface.clearOutEvents();
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public synchronized boolean isStateActive(State state) {
	
		switch (state) {
		case payment_management_Payment:
			return stateVector[0] == State.payment_management_Payment;
		case drink_management_configuration:
			return stateVector[1] == State.drink_management_configuration;
		case activity_management_configuration:
			return stateVector[2] == State.activity_management_configuration;
		case machine_management_Standby:
			return stateVector[3] == State.machine_management_Standby;
		case machine_management_Cleaning:
			return stateVector[3] == State.machine_management_Cleaning;
		case machine_management_checkingPayment:
			return stateVector[3] == State.machine_management_checkingPayment;
		case machine_management_Preparation:
			return stateVector[3].ordinal() >= State.
					machine_management_Preparation.ordinal()&& stateVector[3].ordinal() <= State.machine_management_Preparation_r1_step4_r1_sync.ordinal();
		case machine_management_Preparation_r1_step1:
			return stateVector[3].ordinal() >= State.
					machine_management_Preparation_r1_step1.ordinal()&& stateVector[3].ordinal() <= State.machine_management_Preparation_r1_step1_r2_sync.ordinal();
		case machine_management_Preparation_r1_step1_r1_Expresso:
			return stateVector[3] == State.machine_management_Preparation_r1_step1_r1_Expresso;
		case machine_management_Preparation_r1_step1_r1_sync:
			return stateVector[3] == State.machine_management_Preparation_r1_step1_r1_sync;
		case machine_management_Preparation_r1_step1_r2_General:
			return stateVector[4] == State.machine_management_Preparation_r1_step1_r2_General;
		case machine_management_Preparation_r1_step1_r2_sync:
			return stateVector[4] == State.machine_management_Preparation_r1_step1_r2_sync;
		case machine_management_Preparation_r1_step2:
			return stateVector[3].ordinal() >= State.
					machine_management_Preparation_r1_step2.ordinal()&& stateVector[3].ordinal() <= State.machine_management_Preparation_r1_step2_r2_General.ordinal();
		case machine_management_Preparation_r1_step2_r1_sync:
			return stateVector[3] == State.machine_management_Preparation_r1_step2_r1_sync;
		case machine_management_Preparation_r1_step2_r2_General:
			return stateVector[4] == State.machine_management_Preparation_r1_step2_r2_General;
		case machine_management_Preparation_r1_step3:
			return stateVector[3].ordinal() >= State.
					machine_management_Preparation_r1_step3.ordinal()&& stateVector[3].ordinal() <= State.machine_management_Preparation_r1_step3_r2_option.ordinal();
		case machine_management_Preparation_r1_step3_r1_Tea1:
			return stateVector[3] == State.machine_management_Preparation_r1_step3_r1_Tea1;
		case machine_management_Preparation_r1_step3_r1_sync:
			return stateVector[3] == State.machine_management_Preparation_r1_step3_r1_sync;
		case machine_management_Preparation_r1_step3_r1_tea2_small:
			return stateVector[3] == State.machine_management_Preparation_r1_step3_r1_tea2_small;
		case machine_management_Preparation_r1_step3_r1_tea2_medium:
			return stateVector[3] == State.machine_management_Preparation_r1_step3_r1_tea2_medium;
		case machine_management_Preparation_r1_step3_r1_tea2_big:
			return stateVector[3] == State.machine_management_Preparation_r1_step3_r1_tea2_big;
		case machine_management_Preparation_r1_step3_r1_soup_option:
			return stateVector[3] == State.machine_management_Preparation_r1_step3_r1_soup_option;
		case machine_management_Preparation_r1_step3_r2_General:
			return stateVector[4] == State.machine_management_Preparation_r1_step3_r2_General;
		case machine_management_Preparation_r1_step3_r2_sync:
			return stateVector[4] == State.machine_management_Preparation_r1_step3_r2_sync;
		case machine_management_Preparation_r1_step3_r2_option:
			return stateVector[4] == State.machine_management_Preparation_r1_step3_r2_option;
		case machine_management_Preparation_r1_step4:
			return stateVector[3].ordinal() >= State.
					machine_management_Preparation_r1_step4.ordinal()&& stateVector[3].ordinal() <= State.machine_management_Preparation_r1_step4_r1_sync.ordinal();
		case machine_management_Preparation_r1_step4_r1_cooling1:
			return stateVector[3] == State.machine_management_Preparation_r1_step4_r1_cooling1;
		case machine_management_Preparation_r1_step4_r1_sync:
			return stateVector[3] == State.machine_management_Preparation_r1_step4_r1_sync;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public synchronized void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public synchronized void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	private void raiseResetMachineInternal() {
		synchronized(DrinkingfactoryStatemachine.this) {
			resetMachineInternal = true;
		}
	}
	
	private void raiseUserActionInternal() {
		synchronized(DrinkingfactoryStatemachine.this) {
			userActionInternal = true;
		}
	}
	
	private void raiseDrinkSelected() {
		synchronized(DrinkingfactoryStatemachine.this) {
			drinkSelected = true;
		}
	}
	
	public synchronized void raiseAddMoney() {
		sCInterface.raiseAddMoney();
	}
	
	public synchronized void raisePaying() {
		sCInterface.raisePaying();
	}
	
	public synchronized void raisePaymentValidate() {
		sCInterface.raisePaymentValidate();
	}
	
	public synchronized void raiseResetMachine() {
		sCInterface.raiseResetMachine();
	}
	
	public synchronized void raiseUserAction() {
		sCInterface.raiseUserAction();
	}
	
	public synchronized void raiseCupGrabbed() {
		sCInterface.raiseCupGrabbed();
	}
	
	public synchronized void raiseTempReached() {
		sCInterface.raiseTempReached();
	}
	
	public synchronized void raiseCupFilled() {
		sCInterface.raiseCupFilled();
	}
	
	public synchronized void raiseCoffeeSelected() {
		sCInterface.raiseCoffeeSelected();
	}
	
	public synchronized void raiseTeaSelected() {
		sCInterface.raiseTeaSelected();
	}
	
	public synchronized void raiseEspressoSelected() {
		sCInterface.raiseEspressoSelected();
	}
	
	public synchronized void raiseSoupSelected() {
		sCInterface.raiseSoupSelected();
	}
	
	public synchronized void raiseIcedTeaSelected() {
		sCInterface.raiseIcedTeaSelected();
	}
	
	public synchronized boolean isRaisedDoResetMoney() {
		return sCInterface.isRaisedDoResetMoney();
	}
	
	public synchronized boolean isRaisedDoResetMachine() {
		return sCInterface.isRaisedDoResetMachine();
	}
	
	public synchronized boolean isRaisedDoCleaning() {
		return sCInterface.isRaisedDoCleaning();
	}
	
	public synchronized boolean isRaisedGrindBeans() {
		return sCInterface.isRaisedGrindBeans();
	}
	
	public synchronized boolean isRaisedTakeTeaBag() {
		return sCInterface.isRaisedTakeTeaBag();
	}
	
	public synchronized boolean isRaisedTakeOffTeaBag() {
		return sCInterface.isRaisedTakeOffTeaBag();
	}
	
	public synchronized boolean isRaisedTakeCoffeePod() {
		return sCInterface.isRaisedTakeCoffeePod();
	}
	
	public synchronized boolean isRaisedHeatWater() {
		return sCInterface.isRaisedHeatWater();
	}
	
	public synchronized boolean isRaisedPutCup() {
		return sCInterface.isRaisedPutCup();
	}
	
	public synchronized boolean isRaisedAddSugar() {
		return sCInterface.isRaisedAddSugar();
	}
	
	public synchronized boolean isRaisedPourWater() {
		return sCInterface.isRaisedPourWater();
	}
	
	public synchronized boolean isRaisedPutBeans() {
		return sCInterface.isRaisedPutBeans();
	}
	
	public synchronized boolean isRaisedCheckPayment() {
		return sCInterface.isRaisedCheckPayment();
	}
	
	public synchronized boolean isRaisedCheckStocks() {
		return sCInterface.isRaisedCheckStocks();
	}
	
	public synchronized boolean isRaisedDisplayOptions() {
		return sCInterface.isRaisedDisplayOptions();
	}
	
	public synchronized boolean isRaisedPourMilk() {
		return sCInterface.isRaisedPourMilk();
	}
	
	public synchronized boolean isRaisedPourSyrup() {
		return sCInterface.isRaisedPourSyrup();
	}
	
	public synchronized boolean isRaisedAddBread() {
		return sCInterface.isRaisedAddBread();
	}
	
	public synchronized boolean isRaisedAddIceCream() {
		return sCInterface.isRaisedAddIceCream();
	}
	
	public synchronized boolean isRaisedPourSoup() {
		return sCInterface.isRaisedPourSoup();
	}
	
	public synchronized boolean isRaisedPutSpice() {
		return sCInterface.isRaisedPutSpice();
	}
	
	public synchronized boolean isRaisedLockDoor() {
		return sCInterface.isRaisedLockDoor();
	}
	
	public synchronized boolean isRaisedUnlockDoor() {
		return sCInterface.isRaisedUnlockDoor();
	}
	
	public synchronized boolean isRaisedNitrogenInjection() {
		return sCInterface.isRaisedNitrogenInjection();
	}
	
	public synchronized String getDrinkName() {
		return sCInterface.getDrinkName();
	}
	
	public synchronized void setDrinkName(String value) {
		sCInterface.setDrinkName(value);
	}
	
	public synchronized String getDrinkSize() {
		return sCInterface.getDrinkSize();
	}
	
	public synchronized void setDrinkSize(String value) {
		sCInterface.setDrinkSize(value);
	}
	
	public synchronized boolean getOptionDrink() {
		return sCInterface.getOptionDrink();
	}
	
	public synchronized void setOptionDrink(boolean value) {
		sCInterface.setOptionDrink(value);
	}
	
	public synchronized boolean getOptionSugar() {
		return sCInterface.getOptionSugar();
	}
	
	public synchronized void setOptionSugar(boolean value) {
		sCInterface.setOptionSugar(value);
	}
	
	public synchronized boolean getOptionIceCream() {
		return sCInterface.getOptionIceCream();
	}
	
	public synchronized void setOptionIceCream(boolean value) {
		sCInterface.setOptionIceCream(value);
	}
	
	public synchronized long getProgress() {
		return sCInterface.getProgress();
	}
	
	public synchronized void setProgress(long value) {
		sCInterface.setProgress(value);
	}
	
	public synchronized boolean getCupPlaced() {
		return sCInterface.getCupPlaced();
	}
	
	public synchronized void setCupPlaced(boolean value) {
		sCInterface.setCupPlaced(value);
	}
	
	private boolean check_machine_management_Preparation_r1_step1_r1__choice_0_tr0_tr0() {
		return ((sCInterface.getDrinkName()== null?"tea" ==null :sCInterface.getDrinkName().equals("tea")) || (sCInterface.getDrinkName()== null?"icedTea" ==null :sCInterface.getDrinkName().equals("icedTea")));
	}
	
	private boolean check_machine_management_Preparation_r1_step1_r1__choice_0_tr1_tr1() {
		return (sCInterface.getDrinkName()== null?"coffee" ==null :sCInterface.getDrinkName().equals("coffee"));
	}
	
	private boolean check_machine_management_Preparation_r1_step1_r1__choice_0_tr2_tr2() {
		return (sCInterface.getDrinkName()== null?"espresso" ==null :sCInterface.getDrinkName().equals("espresso"));
	}
	
	private boolean check_machine_management_Preparation_r1_step1_r1__choice_0_tr4_tr4() {
		return (sCInterface.getDrinkName()== null?"soup" ==null :sCInterface.getDrinkName().equals("soup"));
	}
	
	private boolean check_machine_management_Preparation_r1_step1_r1__choice_1_tr0_tr0() {
		return !sCInterface.getCupPlaced();
	}
	
	private boolean check_machine_management_Preparation_r1_step2_r1__choice_0_tr0_tr0() {
		return (sCInterface.getDrinkName()== null?"coffee" ==null :sCInterface.getDrinkName().equals("coffee"));
	}
	
	private boolean check_machine_management_Preparation_r1_step2_r1__choice_0_tr1_tr1() {
		return (sCInterface.getDrinkName()== null?"espresso" ==null :sCInterface.getDrinkName().equals("espresso"));
	}
	
	private boolean check_machine_management_Preparation_r1_step2_r1__choice_0_tr2_tr2() {
		return ((sCInterface.getDrinkName()== null?"tea" ==null :sCInterface.getDrinkName().equals("tea")) || (sCInterface.getDrinkName()== null?"icedTea" ==null :sCInterface.getDrinkName().equals("icedTea")));
	}
	
	private boolean check_machine_management_Preparation_r1_step2_r1__choice_0_tr4_tr4() {
		return (sCInterface.getDrinkName()== null?"soup" ==null :sCInterface.getDrinkName().equals("soup"));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r1__choice_0_tr0_tr0() {
		return (sCInterface.getDrinkName()== null?"espresso" ==null :sCInterface.getDrinkName().equals("espresso"));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r1__choice_0_tr1_tr1() {
		return ((sCInterface.getDrinkName()== null?"tea" ==null :sCInterface.getDrinkName().equals("tea")) || (sCInterface.getDrinkName()== null?"icedTea" ==null :sCInterface.getDrinkName().equals("icedTea")));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r1__choice_0_tr2_tr2() {
		return (sCInterface.getDrinkName()== null?"coffee" ==null :sCInterface.getDrinkName().equals("coffee"));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r1__choice_0_tr4_tr4() {
		return (sCInterface.getDrinkName()== null?"soup" ==null :sCInterface.getDrinkName().equals("soup"));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r1__choice_1_tr0_tr0() {
		return (sCInterface.getDrinkSize()== null?"small" ==null :sCInterface.getDrinkSize().equals("small"));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r1__choice_1_tr1_tr1() {
		return (sCInterface.getDrinkSize()== null?"medium" ==null :sCInterface.getDrinkSize().equals("medium"));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r1__choice_1_tr2_tr2() {
		return (sCInterface.getDrinkSize()== null?"big" ==null :sCInterface.getDrinkSize().equals("big"));
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r2__choice_0_tr0_tr0() {
		return sCInterface.getOptionSugar();
	}
	
	private boolean check_machine_management_Preparation_r1_step3_r2__choice_1_tr0_tr0() {
		return ((((sCInterface.getDrinkName()== null?"coffee" ==null :sCInterface.getDrinkName().equals("coffee")) || (sCInterface.getDrinkName()== null?"espresso" ==null :sCInterface.getDrinkName().equals("espresso")))) && sCInterface.getOptionIceCream());
	}
	
	private boolean check_machine_management_Preparation_r1_step4_r1__choice_0_tr1_tr1() {
		return (sCInterface.getDrinkName()== null?"icedTea" ==null :sCInterface.getDrinkName().equals("icedTea"));
	}
	
	private boolean check_machine_management_Preparation_r1_step4_r1__choice_1_tr0_tr0() {
		return sCInterface.getOptionDrink();
	}
	
	private void effect_machine_management_Preparation_tr0() {
		exitSequence_machine_management_Preparation();
		enterSequence_machine_management_Cleaning_default();
		react();
	}
	
	private void effect_machine_management_Preparation_r1_step1_r1__choice_0_tr0() {
		sCInterface.raiseTakeTeaBag();
		
		enterSequence_machine_management_Preparation_r1_step1_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step1_r1__choice_0_tr1() {
		sCInterface.raiseTakeCoffeePod();
		
		enterSequence_machine_management_Preparation_r1_step1_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step1_r1__choice_0_tr2() {
		enterSequence_machine_management_Preparation_r1_step1_r1_Expresso_default();
	}
	
	private void effect_machine_management_Preparation_r1_step1_r1__choice_0_tr4() {
		react_machine_management_Preparation_r1_step1_r1__choice_1();
	}
	
	private void effect_machine_management_Preparation_r1_step1_r1__choice_0_tr3() {
		enterSequence_machine_management_Preparation_r1_step1_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step1_r1__choice_1_tr0() {
		sCInterface.raisePutCup();
		
		sCInterface.setCupPlaced(true);
		
		enterSequence_machine_management_Preparation_r1_step1_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step1_r1__choice_1_tr1() {
		enterSequence_machine_management_Preparation_r1_step1_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step2_r1__choice_0_tr0() {
		enterSequence_machine_management_Preparation_r1_step2_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step2_r1__choice_0_tr1() {
		sCInterface.raisePutBeans();
		
		enterSequence_machine_management_Preparation_r1_step2_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step2_r1__choice_0_tr2() {
		enterSequence_machine_management_Preparation_r1_step2_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step2_r1__choice_0_tr4() {
		sCInterface.raisePourSoup();
		
		sCInterface.raisePutSpice();
		
		enterSequence_machine_management_Preparation_r1_step2_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step2_r1__choice_0_tr3() {
		enterSequence_machine_management_Preparation_r1_step2_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_0_tr0() {
		enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_0_tr1() {
		enterSequence_machine_management_Preparation_r1_step3_r1_Tea1_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_0_tr2() {
		enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_0_tr4() {
		enterSequence_machine_management_Preparation_r1_step3_r1_soup_option_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_0_tr3() {
		enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_1_tr0() {
		enterSequence_machine_management_Preparation_r1_step3_r1_tea2_small_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_1_tr1() {
		enterSequence_machine_management_Preparation_r1_step3_r1_tea2_medium_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_1_tr2() {
		enterSequence_machine_management_Preparation_r1_step3_r1_tea2_big_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r1__choice_1_tr3() {
		sCInterface.raiseTakeOffTeaBag();
		
		enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r2__choice_0_tr0() {
		sCInterface.raisePourSyrup();
		
		enterSequence_machine_management_Preparation_r1_step3_r2_option_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r2__choice_0_tr1() {
		enterSequence_machine_management_Preparation_r1_step3_r2_option_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r2__choice_1_tr0() {
		sCInterface.raiseAddIceCream();
		
		enterSequence_machine_management_Preparation_r1_step3_r2_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step3_r2__choice_1_tr1() {
		enterSequence_machine_management_Preparation_r1_step3_r2_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step4_r1__choice_0_tr1() {
		sCInterface.raiseLockDoor();
		
		enterSequence_machine_management_Preparation_r1_step4_r1_cooling1_default();
	}
	
	private void effect_machine_management_Preparation_r1_step4_r1__choice_0_tr0() {
		react_machine_management_Preparation_r1_step4_r1__choice_1();
	}
	
	private void effect_machine_management_Preparation_r1_step4_r1__choice_1_tr0() {
		sCInterface.raisePourMilk();
		
		enterSequence_machine_management_Preparation_r1_step4_r1_sync_default();
	}
	
	private void effect_machine_management_Preparation_r1_step4_r1__choice_1_tr1() {
		enterSequence_machine_management_Preparation_r1_step4_r1_sync_default();
	}
	
	/* Entry action for state 'Payment'. */
	private void entryAction_payment_management_Payment() {
		sCInterface.raiseCheckPayment();
		
		raiseUserActionInternal();
	}
	
	/* Entry action for state 'configuration'. */
	private void entryAction_drink_management_configuration() {
		sCInterface.raiseCheckPayment();
		
		raiseUserActionInternal();
		
		sCInterface.raiseDisplayOptions();
	}
	
	/* Entry action for state 'configuration'. */
	private void entryAction_activity_management_configuration() {
		timer.setTimer(this, 0, (45 * 1000), false);
	}
	
	/* Entry action for state 'Standby'. */
	private void entryAction_machine_management_Standby() {
		sCInterface.raiseDoResetMachine();
		
		sCInterface.raiseCheckStocks();
		
		sCInterface.setProgress(0);
	}
	
	/* Entry action for state 'Cleaning'. */
	private void entryAction_machine_management_Cleaning() {
		timer.setTimer(this, 1, (5 * 1000), false);
		
		sCInterface.setDrinkName("none");
		
		sCInterface.setDrinkSize("none");
		
		sCInterface.raiseDoCleaning();
	}
	
	/* Entry action for state 'Expresso'. */
	private void entryAction_machine_management_Preparation_r1_step1_r1_Expresso() {
		timer.setTimer(this, 2, (10 * 1000), false);
		
		sCInterface.raiseGrindBeans();
	}
	
	/* Entry action for state 'sync'. */
	private void entryAction_machine_management_Preparation_r1_step1_r1_sync() {
		sCInterface.setProgress(sCInterface.getProgress() + 15);
	}
	
	/* Entry action for state 'General'. */
	private void entryAction_machine_management_Preparation_r1_step1_r2_General() {
		sCInterface.raiseHeatWater();
	}
	
	/* Entry action for state 'sync'. */
	private void entryAction_machine_management_Preparation_r1_step1_r2_sync() {
		sCInterface.setProgress(sCInterface.getProgress() + 15);
	}
	
	/* Entry action for state 'sync'. */
	private void entryAction_machine_management_Preparation_r1_step2_r1_sync() {
		sCInterface.setProgress(sCInterface.getProgress() + 30);
	}
	
	/* Entry action for state 'General'. */
	private void entryAction_machine_management_Preparation_r1_step2_r2_General() {
		if (!sCInterface.getCupPlaced()) {
			sCInterface.raisePutCup();
			
			sCInterface.setCupPlaced(true);
		}
	}
	
	/* Entry action for state 'Tea1'. */
	private void entryAction_machine_management_Preparation_r1_step3_r1_Tea1() {
		sCInterface.setProgress(sCInterface.getProgress() + 10);
	}
	
	/* Entry action for state 'sync'. */
	private void entryAction_machine_management_Preparation_r1_step3_r1_sync() {
		sCInterface.setProgress(sCInterface.getProgress() + 10);
	}
	
	/* Entry action for state 'tea2_small'. */
	private void entryAction_machine_management_Preparation_r1_step3_r1_tea2_small() {
		timer.setTimer(this, 3, (10 * 1000), false);
	}
	
	/* Entry action for state 'tea2_medium'. */
	private void entryAction_machine_management_Preparation_r1_step3_r1_tea2_medium() {
		timer.setTimer(this, 4, (20 * 1000), false);
	}
	
	/* Entry action for state 'tea2_big'. */
	private void entryAction_machine_management_Preparation_r1_step3_r1_tea2_big() {
		timer.setTimer(this, 5, (30 * 1000), false);
	}
	
	/* Entry action for state 'soup option'. */
	private void entryAction_machine_management_Preparation_r1_step3_r1_soup_option() {
		timer.setTimer(this, 6, (3 * 1000), false);
	}
	
	/* Entry action for state 'General'. */
	private void entryAction_machine_management_Preparation_r1_step3_r2_General() {
		sCInterface.raisePourWater();
		
		sCInterface.raiseAddSugar();
	}
	
	/* Entry action for state 'sync'. */
	private void entryAction_machine_management_Preparation_r1_step3_r2_sync() {
		sCInterface.setProgress(sCInterface.getProgress() + 10);
	}
	
	/* Entry action for state 'cooling1'. */
	private void entryAction_machine_management_Preparation_r1_step4_r1_cooling1() {
		sCInterface.raiseNitrogenInjection();
		
		sCInterface.setProgress(95);
	}
	
	/* Entry action for state 'sync'. */
	private void entryAction_machine_management_Preparation_r1_step4_r1_sync() {
		sCInterface.setProgress(100);
	}
	
	/* Exit action for state 'configuration'. */
	private void exitAction_activity_management_configuration() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Cleaning'. */
	private void exitAction_machine_management_Cleaning() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Expresso'. */
	private void exitAction_machine_management_Preparation_r1_step1_r1_Expresso() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'tea2_small'. */
	private void exitAction_machine_management_Preparation_r1_step3_r1_tea2_small() {
		timer.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'tea2_medium'. */
	private void exitAction_machine_management_Preparation_r1_step3_r1_tea2_medium() {
		timer.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'tea2_big'. */
	private void exitAction_machine_management_Preparation_r1_step3_r1_tea2_big() {
		timer.unsetTimer(this, 5);
	}
	
	/* Exit action for state 'soup option'. */
	private void exitAction_machine_management_Preparation_r1_step3_r1_soup_option() {
		timer.unsetTimer(this, 6);
	}
	
	/* 'default' enter sequence for state Payment */
	private void enterSequence_payment_management_Payment_default() {
		entryAction_payment_management_Payment();
		nextStateIndex = 0;
		stateVector[0] = State.payment_management_Payment;
	}
	
	/* 'default' enter sequence for state configuration */
	private void enterSequence_drink_management_configuration_default() {
		entryAction_drink_management_configuration();
		nextStateIndex = 1;
		stateVector[1] = State.drink_management_configuration;
	}
	
	/* 'default' enter sequence for state configuration */
	private void enterSequence_activity_management_configuration_default() {
		entryAction_activity_management_configuration();
		nextStateIndex = 2;
		stateVector[2] = State.activity_management_configuration;
	}
	
	/* 'default' enter sequence for state Standby */
	private void enterSequence_machine_management_Standby_default() {
		entryAction_machine_management_Standby();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Standby;
	}
	
	/* 'default' enter sequence for state Cleaning */
	private void enterSequence_machine_management_Cleaning_default() {
		entryAction_machine_management_Cleaning();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Cleaning;
	}
	
	/* 'default' enter sequence for state checkingPayment */
	private void enterSequence_machine_management_checkingPayment_default() {
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_checkingPayment;
	}
	
	/* 'default' enter sequence for state Preparation */
	private void enterSequence_machine_management_Preparation_default() {
		enterSequence_machine_management_Preparation_r1_default();
	}
	
	/* 'default' enter sequence for state step1 */
	private void enterSequence_machine_management_Preparation_r1_step1_default() {
		enterSequence_machine_management_Preparation_r1_step1_r1_default();
		enterSequence_machine_management_Preparation_r1_step1_r2_default();
	}
	
	/* 'default' enter sequence for state Expresso */
	private void enterSequence_machine_management_Preparation_r1_step1_r1_Expresso_default() {
		entryAction_machine_management_Preparation_r1_step1_r1_Expresso();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step1_r1_Expresso;
	}
	
	/* 'default' enter sequence for state sync */
	private void enterSequence_machine_management_Preparation_r1_step1_r1_sync_default() {
		entryAction_machine_management_Preparation_r1_step1_r1_sync();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step1_r1_sync;
	}
	
	/* 'default' enter sequence for state General */
	private void enterSequence_machine_management_Preparation_r1_step1_r2_General_default() {
		entryAction_machine_management_Preparation_r1_step1_r2_General();
		nextStateIndex = 4;
		stateVector[4] = State.machine_management_Preparation_r1_step1_r2_General;
	}
	
	/* 'default' enter sequence for state sync */
	private void enterSequence_machine_management_Preparation_r1_step1_r2_sync_default() {
		entryAction_machine_management_Preparation_r1_step1_r2_sync();
		nextStateIndex = 4;
		stateVector[4] = State.machine_management_Preparation_r1_step1_r2_sync;
	}
	
	/* 'default' enter sequence for state step2 */
	private void enterSequence_machine_management_Preparation_r1_step2_default() {
		enterSequence_machine_management_Preparation_r1_step2_r1_default();
		enterSequence_machine_management_Preparation_r1_step2_r2_default();
	}
	
	/* 'default' enter sequence for state sync */
	private void enterSequence_machine_management_Preparation_r1_step2_r1_sync_default() {
		entryAction_machine_management_Preparation_r1_step2_r1_sync();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step2_r1_sync;
	}
	
	/* 'default' enter sequence for state General */
	private void enterSequence_machine_management_Preparation_r1_step2_r2_General_default() {
		entryAction_machine_management_Preparation_r1_step2_r2_General();
		nextStateIndex = 4;
		stateVector[4] = State.machine_management_Preparation_r1_step2_r2_General;
	}
	
	/* 'default' enter sequence for state step3 */
	private void enterSequence_machine_management_Preparation_r1_step3_default() {
		enterSequence_machine_management_Preparation_r1_step3_r1_default();
		enterSequence_machine_management_Preparation_r1_step3_r2_default();
	}
	
	/* 'default' enter sequence for state Tea1 */
	private void enterSequence_machine_management_Preparation_r1_step3_r1_Tea1_default() {
		entryAction_machine_management_Preparation_r1_step3_r1_Tea1();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step3_r1_Tea1;
	}
	
	/* 'default' enter sequence for state sync */
	private void enterSequence_machine_management_Preparation_r1_step3_r1_sync_default() {
		entryAction_machine_management_Preparation_r1_step3_r1_sync();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step3_r1_sync;
	}
	
	/* 'default' enter sequence for state tea2_small */
	private void enterSequence_machine_management_Preparation_r1_step3_r1_tea2_small_default() {
		entryAction_machine_management_Preparation_r1_step3_r1_tea2_small();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step3_r1_tea2_small;
	}
	
	/* 'default' enter sequence for state tea2_medium */
	private void enterSequence_machine_management_Preparation_r1_step3_r1_tea2_medium_default() {
		entryAction_machine_management_Preparation_r1_step3_r1_tea2_medium();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step3_r1_tea2_medium;
	}
	
	/* 'default' enter sequence for state tea2_big */
	private void enterSequence_machine_management_Preparation_r1_step3_r1_tea2_big_default() {
		entryAction_machine_management_Preparation_r1_step3_r1_tea2_big();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step3_r1_tea2_big;
	}
	
	/* 'default' enter sequence for state soup option */
	private void enterSequence_machine_management_Preparation_r1_step3_r1_soup_option_default() {
		entryAction_machine_management_Preparation_r1_step3_r1_soup_option();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step3_r1_soup_option;
	}
	
	/* 'default' enter sequence for state General */
	private void enterSequence_machine_management_Preparation_r1_step3_r2_General_default() {
		entryAction_machine_management_Preparation_r1_step3_r2_General();
		nextStateIndex = 4;
		stateVector[4] = State.machine_management_Preparation_r1_step3_r2_General;
	}
	
	/* 'default' enter sequence for state sync */
	private void enterSequence_machine_management_Preparation_r1_step3_r2_sync_default() {
		entryAction_machine_management_Preparation_r1_step3_r2_sync();
		nextStateIndex = 4;
		stateVector[4] = State.machine_management_Preparation_r1_step3_r2_sync;
	}
	
	/* 'default' enter sequence for state option */
	private void enterSequence_machine_management_Preparation_r1_step3_r2_option_default() {
		nextStateIndex = 4;
		stateVector[4] = State.machine_management_Preparation_r1_step3_r2_option;
	}
	
	/* 'default' enter sequence for state cooling1 */
	private void enterSequence_machine_management_Preparation_r1_step4_r1_cooling1_default() {
		entryAction_machine_management_Preparation_r1_step4_r1_cooling1();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step4_r1_cooling1;
	}
	
	/* 'default' enter sequence for state sync */
	private void enterSequence_machine_management_Preparation_r1_step4_r1_sync_default() {
		entryAction_machine_management_Preparation_r1_step4_r1_sync();
		nextStateIndex = 3;
		stateVector[3] = State.machine_management_Preparation_r1_step4_r1_sync;
	}
	
	/* 'default' enter sequence for region payment management */
	private void enterSequence_payment_management_default() {
		react_payment_management__entry_Default();
	}
	
	/* 'default' enter sequence for region drink management */
	private void enterSequence_drink_management_default() {
		react_drink_management__entry_Default();
	}
	
	/* 'default' enter sequence for region activity management */
	private void enterSequence_activity_management_default() {
		react_activity_management__entry_Default();
	}
	
	/* 'default' enter sequence for region machine management */
	private void enterSequence_machine_management_default() {
		react_machine_management__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_machine_management_Preparation_r1_default() {
		react_machine_management_Preparation_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_machine_management_Preparation_r1_step1_r1_default() {
		react_machine_management_Preparation_r1_step1_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_machine_management_Preparation_r1_step1_r2_default() {
		react_machine_management_Preparation_r1_step1_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_machine_management_Preparation_r1_step2_r1_default() {
		react_machine_management_Preparation_r1_step2_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_machine_management_Preparation_r1_step2_r2_default() {
		react_machine_management_Preparation_r1_step2_r2__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_machine_management_Preparation_r1_step3_r1_default() {
		react_machine_management_Preparation_r1_step3_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region r2 */
	private void enterSequence_machine_management_Preparation_r1_step3_r2_default() {
		react_machine_management_Preparation_r1_step3_r2__entry_Default();
	}
	
	/* Default exit sequence for state Payment */
	private void exitSequence_payment_management_Payment() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state configuration */
	private void exitSequence_drink_management_configuration() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state configuration */
	private void exitSequence_activity_management_configuration() {
		nextStateIndex = 2;
		stateVector[2] = State.$NullState$;
		
		exitAction_activity_management_configuration();
	}
	
	/* Default exit sequence for state Standby */
	private void exitSequence_machine_management_Standby() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state Cleaning */
	private void exitSequence_machine_management_Cleaning() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
		
		exitAction_machine_management_Cleaning();
	}
	
	/* Default exit sequence for state checkingPayment */
	private void exitSequence_machine_management_checkingPayment() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state Preparation */
	private void exitSequence_machine_management_Preparation() {
		exitSequence_machine_management_Preparation_r1();
	}
	
	/* Default exit sequence for state step1 */
	private void exitSequence_machine_management_Preparation_r1_step1() {
		exitSequence_machine_management_Preparation_r1_step1_r1();
		exitSequence_machine_management_Preparation_r1_step1_r2();
	}
	
	/* Default exit sequence for state Expresso */
	private void exitSequence_machine_management_Preparation_r1_step1_r1_Expresso() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
		
		exitAction_machine_management_Preparation_r1_step1_r1_Expresso();
	}
	
	/* Default exit sequence for state sync */
	private void exitSequence_machine_management_Preparation_r1_step1_r1_sync() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state General */
	private void exitSequence_machine_management_Preparation_r1_step1_r2_General() {
		nextStateIndex = 4;
		stateVector[4] = State.$NullState$;
	}
	
	/* Default exit sequence for state sync */
	private void exitSequence_machine_management_Preparation_r1_step1_r2_sync() {
		nextStateIndex = 4;
		stateVector[4] = State.$NullState$;
	}
	
	/* Default exit sequence for state step2 */
	private void exitSequence_machine_management_Preparation_r1_step2() {
		exitSequence_machine_management_Preparation_r1_step2_r1();
		exitSequence_machine_management_Preparation_r1_step2_r2();
	}
	
	/* Default exit sequence for state sync */
	private void exitSequence_machine_management_Preparation_r1_step2_r1_sync() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state General */
	private void exitSequence_machine_management_Preparation_r1_step2_r2_General() {
		nextStateIndex = 4;
		stateVector[4] = State.$NullState$;
	}
	
	/* Default exit sequence for state step3 */
	private void exitSequence_machine_management_Preparation_r1_step3() {
		exitSequence_machine_management_Preparation_r1_step3_r1();
		exitSequence_machine_management_Preparation_r1_step3_r2();
	}
	
	/* Default exit sequence for state Tea1 */
	private void exitSequence_machine_management_Preparation_r1_step3_r1_Tea1() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state sync */
	private void exitSequence_machine_management_Preparation_r1_step3_r1_sync() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state tea2_small */
	private void exitSequence_machine_management_Preparation_r1_step3_r1_tea2_small() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
		
		exitAction_machine_management_Preparation_r1_step3_r1_tea2_small();
	}
	
	/* Default exit sequence for state tea2_medium */
	private void exitSequence_machine_management_Preparation_r1_step3_r1_tea2_medium() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
		
		exitAction_machine_management_Preparation_r1_step3_r1_tea2_medium();
	}
	
	/* Default exit sequence for state tea2_big */
	private void exitSequence_machine_management_Preparation_r1_step3_r1_tea2_big() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
		
		exitAction_machine_management_Preparation_r1_step3_r1_tea2_big();
	}
	
	/* Default exit sequence for state soup option */
	private void exitSequence_machine_management_Preparation_r1_step3_r1_soup_option() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
		
		exitAction_machine_management_Preparation_r1_step3_r1_soup_option();
	}
	
	/* Default exit sequence for state General */
	private void exitSequence_machine_management_Preparation_r1_step3_r2_General() {
		nextStateIndex = 4;
		stateVector[4] = State.$NullState$;
	}
	
	/* Default exit sequence for state sync */
	private void exitSequence_machine_management_Preparation_r1_step3_r2_sync() {
		nextStateIndex = 4;
		stateVector[4] = State.$NullState$;
	}
	
	/* Default exit sequence for state option */
	private void exitSequence_machine_management_Preparation_r1_step3_r2_option() {
		nextStateIndex = 4;
		stateVector[4] = State.$NullState$;
	}
	
	/* Default exit sequence for state step4 */
	private void exitSequence_machine_management_Preparation_r1_step4() {
		exitSequence_machine_management_Preparation_r1_step4_r1();
	}
	
	/* Default exit sequence for state cooling1 */
	private void exitSequence_machine_management_Preparation_r1_step4_r1_cooling1() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for state sync */
	private void exitSequence_machine_management_Preparation_r1_step4_r1_sync() {
		nextStateIndex = 3;
		stateVector[3] = State.$NullState$;
	}
	
	/* Default exit sequence for region payment management */
	private void exitSequence_payment_management() {
		switch (stateVector[0]) {
		case payment_management_Payment:
			exitSequence_payment_management_Payment();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region drink management */
	private void exitSequence_drink_management() {
		switch (stateVector[1]) {
		case drink_management_configuration:
			exitSequence_drink_management_configuration();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region activity management */
	private void exitSequence_activity_management() {
		switch (stateVector[2]) {
		case activity_management_configuration:
			exitSequence_activity_management_configuration();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region machine management */
	private void exitSequence_machine_management() {
		switch (stateVector[3]) {
		case machine_management_Standby:
			exitSequence_machine_management_Standby();
			break;
		case machine_management_Cleaning:
			exitSequence_machine_management_Cleaning();
			break;
		case machine_management_checkingPayment:
			exitSequence_machine_management_checkingPayment();
			break;
		case machine_management_Preparation_r1_step1_r1_Expresso:
			exitSequence_machine_management_Preparation_r1_step1_r1_Expresso();
			break;
		case machine_management_Preparation_r1_step1_r1_sync:
			exitSequence_machine_management_Preparation_r1_step1_r1_sync();
			break;
		case machine_management_Preparation_r1_step2_r1_sync:
			exitSequence_machine_management_Preparation_r1_step2_r1_sync();
			break;
		case machine_management_Preparation_r1_step3_r1_Tea1:
			exitSequence_machine_management_Preparation_r1_step3_r1_Tea1();
			break;
		case machine_management_Preparation_r1_step3_r1_sync:
			exitSequence_machine_management_Preparation_r1_step3_r1_sync();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_small:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_small();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_medium:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_medium();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_big:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_big();
			break;
		case machine_management_Preparation_r1_step3_r1_soup_option:
			exitSequence_machine_management_Preparation_r1_step3_r1_soup_option();
			break;
		case machine_management_Preparation_r1_step4_r1_cooling1:
			exitSequence_machine_management_Preparation_r1_step4_r1_cooling1();
			break;
		case machine_management_Preparation_r1_step4_r1_sync:
			exitSequence_machine_management_Preparation_r1_step4_r1_sync();
			break;
		default:
			break;
		}
		
		switch (stateVector[4]) {
		case machine_management_Preparation_r1_step1_r2_General:
			exitSequence_machine_management_Preparation_r1_step1_r2_General();
			break;
		case machine_management_Preparation_r1_step1_r2_sync:
			exitSequence_machine_management_Preparation_r1_step1_r2_sync();
			break;
		case machine_management_Preparation_r1_step2_r2_General:
			exitSequence_machine_management_Preparation_r1_step2_r2_General();
			break;
		case machine_management_Preparation_r1_step3_r2_General:
			exitSequence_machine_management_Preparation_r1_step3_r2_General();
			break;
		case machine_management_Preparation_r1_step3_r2_sync:
			exitSequence_machine_management_Preparation_r1_step3_r2_sync();
			break;
		case machine_management_Preparation_r1_step3_r2_option:
			exitSequence_machine_management_Preparation_r1_step3_r2_option();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_machine_management_Preparation_r1() {
		switch (stateVector[3]) {
		case machine_management_Preparation_r1_step1_r1_Expresso:
			exitSequence_machine_management_Preparation_r1_step1_r1_Expresso();
			break;
		case machine_management_Preparation_r1_step1_r1_sync:
			exitSequence_machine_management_Preparation_r1_step1_r1_sync();
			break;
		case machine_management_Preparation_r1_step2_r1_sync:
			exitSequence_machine_management_Preparation_r1_step2_r1_sync();
			break;
		case machine_management_Preparation_r1_step3_r1_Tea1:
			exitSequence_machine_management_Preparation_r1_step3_r1_Tea1();
			break;
		case machine_management_Preparation_r1_step3_r1_sync:
			exitSequence_machine_management_Preparation_r1_step3_r1_sync();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_small:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_small();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_medium:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_medium();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_big:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_big();
			break;
		case machine_management_Preparation_r1_step3_r1_soup_option:
			exitSequence_machine_management_Preparation_r1_step3_r1_soup_option();
			break;
		case machine_management_Preparation_r1_step4_r1_cooling1:
			exitSequence_machine_management_Preparation_r1_step4_r1_cooling1();
			break;
		case machine_management_Preparation_r1_step4_r1_sync:
			exitSequence_machine_management_Preparation_r1_step4_r1_sync();
			break;
		default:
			break;
		}
		
		switch (stateVector[4]) {
		case machine_management_Preparation_r1_step1_r2_General:
			exitSequence_machine_management_Preparation_r1_step1_r2_General();
			break;
		case machine_management_Preparation_r1_step1_r2_sync:
			exitSequence_machine_management_Preparation_r1_step1_r2_sync();
			break;
		case machine_management_Preparation_r1_step2_r2_General:
			exitSequence_machine_management_Preparation_r1_step2_r2_General();
			break;
		case machine_management_Preparation_r1_step3_r2_General:
			exitSequence_machine_management_Preparation_r1_step3_r2_General();
			break;
		case machine_management_Preparation_r1_step3_r2_sync:
			exitSequence_machine_management_Preparation_r1_step3_r2_sync();
			break;
		case machine_management_Preparation_r1_step3_r2_option:
			exitSequence_machine_management_Preparation_r1_step3_r2_option();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_machine_management_Preparation_r1_step1_r1() {
		switch (stateVector[3]) {
		case machine_management_Preparation_r1_step1_r1_Expresso:
			exitSequence_machine_management_Preparation_r1_step1_r1_Expresso();
			break;
		case machine_management_Preparation_r1_step1_r1_sync:
			exitSequence_machine_management_Preparation_r1_step1_r1_sync();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_machine_management_Preparation_r1_step1_r2() {
		switch (stateVector[4]) {
		case machine_management_Preparation_r1_step1_r2_General:
			exitSequence_machine_management_Preparation_r1_step1_r2_General();
			break;
		case machine_management_Preparation_r1_step1_r2_sync:
			exitSequence_machine_management_Preparation_r1_step1_r2_sync();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_machine_management_Preparation_r1_step2_r1() {
		switch (stateVector[3]) {
		case machine_management_Preparation_r1_step2_r1_sync:
			exitSequence_machine_management_Preparation_r1_step2_r1_sync();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_machine_management_Preparation_r1_step2_r2() {
		switch (stateVector[4]) {
		case machine_management_Preparation_r1_step2_r2_General:
			exitSequence_machine_management_Preparation_r1_step2_r2_General();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_machine_management_Preparation_r1_step3_r1() {
		switch (stateVector[3]) {
		case machine_management_Preparation_r1_step3_r1_Tea1:
			exitSequence_machine_management_Preparation_r1_step3_r1_Tea1();
			break;
		case machine_management_Preparation_r1_step3_r1_sync:
			exitSequence_machine_management_Preparation_r1_step3_r1_sync();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_small:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_small();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_medium:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_medium();
			break;
		case machine_management_Preparation_r1_step3_r1_tea2_big:
			exitSequence_machine_management_Preparation_r1_step3_r1_tea2_big();
			break;
		case machine_management_Preparation_r1_step3_r1_soup_option:
			exitSequence_machine_management_Preparation_r1_step3_r1_soup_option();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r2 */
	private void exitSequence_machine_management_Preparation_r1_step3_r2() {
		switch (stateVector[4]) {
		case machine_management_Preparation_r1_step3_r2_General:
			exitSequence_machine_management_Preparation_r1_step3_r2_General();
			break;
		case machine_management_Preparation_r1_step3_r2_sync:
			exitSequence_machine_management_Preparation_r1_step3_r2_sync();
			break;
		case machine_management_Preparation_r1_step3_r2_option:
			exitSequence_machine_management_Preparation_r1_step3_r2_option();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_machine_management_Preparation_r1_step4_r1() {
		switch (stateVector[3]) {
		case machine_management_Preparation_r1_step4_r1_cooling1:
			exitSequence_machine_management_Preparation_r1_step4_r1_cooling1();
			break;
		case machine_management_Preparation_r1_step4_r1_sync:
			exitSequence_machine_management_Preparation_r1_step4_r1_sync();
			break;
		default:
			break;
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step1_r1__choice_0() {
		if (check_machine_management_Preparation_r1_step1_r1__choice_0_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step1_r1__choice_0_tr0();
		} else {
			if (check_machine_management_Preparation_r1_step1_r1__choice_0_tr1_tr1()) {
				effect_machine_management_Preparation_r1_step1_r1__choice_0_tr1();
			} else {
				if (check_machine_management_Preparation_r1_step1_r1__choice_0_tr2_tr2()) {
					effect_machine_management_Preparation_r1_step1_r1__choice_0_tr2();
				} else {
					if (check_machine_management_Preparation_r1_step1_r1__choice_0_tr4_tr4()) {
						effect_machine_management_Preparation_r1_step1_r1__choice_0_tr4();
					} else {
						effect_machine_management_Preparation_r1_step1_r1__choice_0_tr3();
					}
				}
			}
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step1_r1__choice_1() {
		if (check_machine_management_Preparation_r1_step1_r1__choice_1_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step1_r1__choice_1_tr0();
		} else {
			effect_machine_management_Preparation_r1_step1_r1__choice_1_tr1();
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step2_r1__choice_0() {
		if (check_machine_management_Preparation_r1_step2_r1__choice_0_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step2_r1__choice_0_tr0();
		} else {
			if (check_machine_management_Preparation_r1_step2_r1__choice_0_tr1_tr1()) {
				effect_machine_management_Preparation_r1_step2_r1__choice_0_tr1();
			} else {
				if (check_machine_management_Preparation_r1_step2_r1__choice_0_tr2_tr2()) {
					effect_machine_management_Preparation_r1_step2_r1__choice_0_tr2();
				} else {
					if (check_machine_management_Preparation_r1_step2_r1__choice_0_tr4_tr4()) {
						effect_machine_management_Preparation_r1_step2_r1__choice_0_tr4();
					} else {
						effect_machine_management_Preparation_r1_step2_r1__choice_0_tr3();
					}
				}
			}
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step3_r1__choice_0() {
		if (check_machine_management_Preparation_r1_step3_r1__choice_0_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step3_r1__choice_0_tr0();
		} else {
			if (check_machine_management_Preparation_r1_step3_r1__choice_0_tr1_tr1()) {
				effect_machine_management_Preparation_r1_step3_r1__choice_0_tr1();
			} else {
				if (check_machine_management_Preparation_r1_step3_r1__choice_0_tr2_tr2()) {
					effect_machine_management_Preparation_r1_step3_r1__choice_0_tr2();
				} else {
					if (check_machine_management_Preparation_r1_step3_r1__choice_0_tr4_tr4()) {
						effect_machine_management_Preparation_r1_step3_r1__choice_0_tr4();
					} else {
						effect_machine_management_Preparation_r1_step3_r1__choice_0_tr3();
					}
				}
			}
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step3_r1__choice_1() {
		if (check_machine_management_Preparation_r1_step3_r1__choice_1_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step3_r1__choice_1_tr0();
		} else {
			if (check_machine_management_Preparation_r1_step3_r1__choice_1_tr1_tr1()) {
				effect_machine_management_Preparation_r1_step3_r1__choice_1_tr1();
			} else {
				if (check_machine_management_Preparation_r1_step3_r1__choice_1_tr2_tr2()) {
					effect_machine_management_Preparation_r1_step3_r1__choice_1_tr2();
				} else {
					effect_machine_management_Preparation_r1_step3_r1__choice_1_tr3();
				}
			}
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step3_r2__choice_0() {
		if (check_machine_management_Preparation_r1_step3_r2__choice_0_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step3_r2__choice_0_tr0();
		} else {
			effect_machine_management_Preparation_r1_step3_r2__choice_0_tr1();
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step3_r2__choice_1() {
		if (check_machine_management_Preparation_r1_step3_r2__choice_1_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step3_r2__choice_1_tr0();
		} else {
			effect_machine_management_Preparation_r1_step3_r2__choice_1_tr1();
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step4_r1__choice_0() {
		if (check_machine_management_Preparation_r1_step4_r1__choice_0_tr1_tr1()) {
			effect_machine_management_Preparation_r1_step4_r1__choice_0_tr1();
		} else {
			effect_machine_management_Preparation_r1_step4_r1__choice_0_tr0();
		}
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1_step4_r1__choice_1() {
		if (check_machine_management_Preparation_r1_step4_r1__choice_1_tr0_tr0()) {
			effect_machine_management_Preparation_r1_step4_r1__choice_1_tr0();
		} else {
			effect_machine_management_Preparation_r1_step4_r1__choice_1_tr1();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_payment_management__entry_Default() {
		enterSequence_payment_management_Payment_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_drink_management__entry_Default() {
		enterSequence_drink_management_configuration_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_activity_management__entry_Default() {
		enterSequence_activity_management_configuration_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management__entry_Default() {
		enterSequence_machine_management_Standby_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management_Preparation_r1_step1_r1__entry_Default() {
		react_machine_management_Preparation_r1_step1_r1__choice_0();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management_Preparation_r1_step1_r2__entry_Default() {
		enterSequence_machine_management_Preparation_r1_step1_r2_General_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management_Preparation_r1__entry_Default() {
		enterSequence_machine_management_Preparation_r1_step1_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management_Preparation_r1_step2_r1__entry_Default() {
		react_machine_management_Preparation_r1_step2_r1__choice_0();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management_Preparation_r1_step2_r2__entry_Default() {
		enterSequence_machine_management_Preparation_r1_step2_r2_General_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management_Preparation_r1_step3_r1__entry_Default() {
		react_machine_management_Preparation_r1_step3_r1__choice_0();
	}
	
	/* Default react sequence for initial entry  */
	private void react_machine_management_Preparation_r1_step3_r2__entry_Default() {
		enterSequence_machine_management_Preparation_r1_step3_r2_General_default();
	}
	
	/* The reactions of exit e. */
	private void react_machine_management_Preparation_r1_e() {
		effect_machine_management_Preparation_tr0();
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1__sync0() {
		enterSequence_machine_management_Preparation_r1_step2_default();
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1__sync1() {
		enterSequence_machine_management_Preparation_r1_step3_default();
	}
	
	/* The reactions of state null. */
	private void react_machine_management_Preparation_r1__sync2() {
		react_machine_management_Preparation_r1_step4_r1__choice_0();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean payment_management_Payment_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.addMoney) {
				exitSequence_payment_management_Payment();
				enterSequence_payment_management_Payment_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean drink_management_configuration_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.coffeeSelected) {
				exitSequence_drink_management_configuration();
				sCInterface.setDrinkName("coffee");
				
				raiseDrinkSelected();
				
				enterSequence_drink_management_configuration_default();
			} else {
				if (sCInterface.teaSelected) {
					exitSequence_drink_management_configuration();
					sCInterface.setDrinkName("tea");
					
					raiseDrinkSelected();
					
					enterSequence_drink_management_configuration_default();
				} else {
					if (sCInterface.espressoSelected) {
						exitSequence_drink_management_configuration();
						sCInterface.setDrinkName("espresso");
						
						raiseDrinkSelected();
						
						enterSequence_drink_management_configuration_default();
					} else {
						if (sCInterface.soupSelected) {
							exitSequence_drink_management_configuration();
							sCInterface.setDrinkName("soup");
							
							raiseDrinkSelected();
							
							enterSequence_drink_management_configuration_default();
						} else {
							if (sCInterface.icedTeaSelected) {
								exitSequence_drink_management_configuration();
								sCInterface.setDrinkName("icedTea");
								
								raiseDrinkSelected();
								
								enterSequence_drink_management_configuration_default();
							} else {
								did_transition = false;
							}
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean activity_management_configuration_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[0]) {
				exitSequence_activity_management_configuration();
				raiseResetMachineInternal();
				
				enterSequence_activity_management_configuration_default();
			} else {
				if ((userActionInternal || sCInterface.userAction)) {
					exitSequence_activity_management_configuration();
					enterSequence_activity_management_configuration_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Standby_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if ((drinkSelected || sCInterface.addMoney)) {
				exitSequence_machine_management_Standby();
				enterSequence_machine_management_checkingPayment_default();
				react();
			} else {
				if (resetMachineInternal) {
					exitSequence_machine_management_Standby();
					enterSequence_machine_management_Standby_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean machine_management_Cleaning_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[1]) {
				exitSequence_machine_management_Cleaning();
				enterSequence_machine_management_Standby_default();
				react();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean machine_management_checkingPayment_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.paymentValidate) {
				exitSequence_machine_management_checkingPayment();
				sCInterface.raiseDoResetMoney();
				
				enterSequence_machine_management_Preparation_default();
				react();
			} else {
				if (resetMachineInternal) {
					exitSequence_machine_management_checkingPayment();
					enterSequence_machine_management_Standby_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step1_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step1_r1_Expresso_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[2]) {
				exitSequence_machine_management_Preparation_r1_step1_r1_Expresso();
				enterSequence_machine_management_Preparation_r1_step1_r1_sync_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step1_r1_sync_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (isStateActive(State.machine_management_Preparation_r1_step1_r2_sync)) {
				exitSequence_machine_management_Preparation_r1_step1();
				react_machine_management_Preparation_r1__sync0();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step1_r2_General_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.tempReached) {
				exitSequence_machine_management_Preparation_r1_step1_r2_General();
				enterSequence_machine_management_Preparation_r1_step1_r2_sync_default();
				machine_management_Preparation_r1_step1_react(false);
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step1_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step1_r2_sync_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (isStateActive(State.machine_management_Preparation_r1_step1_r1_sync)) {
				exitSequence_machine_management_Preparation_r1_step1();
				react_machine_management_Preparation_r1__sync0();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step1_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step2_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step2_r1_sync_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (isStateActive(State.machine_management_Preparation_r1_step2_r2_General)) {
				exitSequence_machine_management_Preparation_r1_step2();
				react_machine_management_Preparation_r1__sync1();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step2_r2_General_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (isStateActive(State.machine_management_Preparation_r1_step2_r1_sync)) {
				exitSequence_machine_management_Preparation_r1_step2();
				react_machine_management_Preparation_r1__sync1();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step2_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r1_Tea1_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.cupFilled) {
				exitSequence_machine_management_Preparation_r1_step3_r1_Tea1();
				react_machine_management_Preparation_r1_step3_r1__choice_1();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r1_sync_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (isStateActive(State.machine_management_Preparation_r1_step3_r2_sync)) {
				exitSequence_machine_management_Preparation_r1_step3();
				react_machine_management_Preparation_r1__sync2();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r1_tea2_small_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[3]) {
				exitSequence_machine_management_Preparation_r1_step3_r1_tea2_small();
				sCInterface.raiseTakeOffTeaBag();
				
				enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r1_tea2_medium_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[4]) {
				exitSequence_machine_management_Preparation_r1_step3_r1_tea2_medium();
				sCInterface.raiseTakeOffTeaBag();
				
				enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r1_tea2_big_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[5]) {
				exitSequence_machine_management_Preparation_r1_step3_r1_tea2_big();
				sCInterface.raiseTakeOffTeaBag();
				
				enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r1_soup_option_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (timeEvents[6]) {
				exitSequence_machine_management_Preparation_r1_step3_r1_soup_option();
				sCInterface.raiseAddBread();
				
				enterSequence_machine_management_Preparation_r1_step3_r1_sync_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r2_General_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			exitSequence_machine_management_Preparation_r1_step3_r2_General();
			react_machine_management_Preparation_r1_step3_r2__choice_0();
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r2_sync_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (isStateActive(State.machine_management_Preparation_r1_step3_r1_sync)) {
				exitSequence_machine_management_Preparation_r1_step3();
				react_machine_management_Preparation_r1__sync2();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step3_r2_option_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.cupFilled) {
				exitSequence_machine_management_Preparation_r1_step3_r2_option();
				react_machine_management_Preparation_r1_step3_r2__choice_1();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step3_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step4_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step4_r1_cooling1_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.tempReached) {
				exitSequence_machine_management_Preparation_r1_step4_r1_cooling1();
				sCInterface.raiseUnlockDoor();
				
				react_machine_management_Preparation_r1_step4_r1__choice_1();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step4_react(try_transition);
		}
		return did_transition;
	}
	
	private boolean machine_management_Preparation_r1_step4_r1_sync_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.cupGrabbed) {
				exitSequence_machine_management_Preparation_r1_step4();
				sCInterface.setCupPlaced(false);
				
				react_machine_management_Preparation_r1_e();
			} else {
				did_transition = false;
			}
		}
		if (did_transition==false) {
			did_transition = machine_management_Preparation_r1_step4_react(try_transition);
		}
		return did_transition;
	}
	
}
