/** Generated by YAKINDU Statechart Tools code generator. */
package drinkingfactory.drinkingfactory;

import drinkingfactory.IStatemachine;
import drinkingfactory.ITimerCallback;
import java.util.List;

public interface IDrinkingfactoryStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseAddMoney();
		
		public void raisePaying();
		
		public void raisePaymentValidate();
		
		public void raiseResetMachine();
		
		public void raiseUserAction();
		
		public void raiseCupGrabbed();
		
		public void raiseTempReached();
		
		public void raiseCupFilled();
		
		public void raiseCoffeeSelected();
		
		public void raiseTeaSelected();
		
		public void raiseEspressoSelected();
		
		public void raiseSoupSelected();
		
		public void raiseIcedTeaSelected();
		
		public boolean isRaisedDoResetMoney();
		
		public boolean isRaisedDoResetMachine();
		
		public boolean isRaisedDoCleaning();
		
		public boolean isRaisedGrindBeans();
		
		public boolean isRaisedTakeTeaBag();
		
		public boolean isRaisedTakeOffTeaBag();
		
		public boolean isRaisedTakeCoffeePod();
		
		public boolean isRaisedHeatWater();
		
		public boolean isRaisedPutCup();
		
		public boolean isRaisedAddSugar();
		
		public boolean isRaisedPourWater();
		
		public boolean isRaisedPutBeans();
		
		public boolean isRaisedCheckPayment();
		
		public boolean isRaisedCheckStocks();
		
		public boolean isRaisedDisplayOptions();
		
		public boolean isRaisedPourMilk();
		
		public boolean isRaisedPourSyrup();
		
		public boolean isRaisedAddBread();
		
		public boolean isRaisedAddIceCream();
		
		public boolean isRaisedPourSoup();
		
		public boolean isRaisedPutSpice();
		
		public boolean isRaisedLockDoor();
		
		public boolean isRaisedUnlockDoor();
		
		public boolean isRaisedNitrogenInjection();
		
		public String getDrinkName();
		
		public void setDrinkName(String value);
		
		public String getDrinkSize();
		
		public void setDrinkSize(String value);
		
		public boolean getOptionDrink();
		
		public void setOptionDrink(boolean value);
		
		public boolean getOptionSugar();
		
		public void setOptionSugar(boolean value);
		
		public boolean getOptionIceCream();
		
		public void setOptionIceCream(boolean value);
		
		public long getProgress();
		
		public void setProgress(long value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoResetMoneyRaised();
		public void onDoResetMachineRaised();
		public void onDoCleaningRaised();
		public void onGrindBeansRaised();
		public void onTakeTeaBagRaised();
		public void onTakeOffTeaBagRaised();
		public void onTakeCoffeePodRaised();
		public void onHeatWaterRaised();
		public void onPutCupRaised();
		public void onAddSugarRaised();
		public void onPourWaterRaised();
		public void onPutBeansRaised();
		public void onCheckPaymentRaised();
		public void onCheckStocksRaised();
		public void onDisplayOptionsRaised();
		public void onPourMilkRaised();
		public void onPourSyrupRaised();
		public void onAddBreadRaised();
		public void onAddIceCreamRaised();
		public void onPourSoupRaised();
		public void onPutSpiceRaised();
		public void onLockDoorRaised();
		public void onUnlockDoorRaised();
		public void onNitrogenInjectionRaised();
		}
	
	public SCInterface getSCInterface();
	
}
