/** Generated by YAKINDU Statechart Tools code generator. */
package drinkingfactory.drinkingfactory;

import drinkingfactory.IStatemachine;
import drinkingfactory.ITimerCallback;
import java.util.List;

public interface IDrinkingfactoryStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseDrinkSelected();
		
		public void raiseAddMoney();
		
		public void raisePaying();
		
		public void raisePaymentValidate();
		
		public void raiseResetMachine();
		
		public void raiseUserAction();
		
		public void raiseCupGrabbed();
		
		public void raiseHeatReached();
		
		public void raiseCupFilled();
		
		public void raiseCoffeeSelected();
		
		public void raiseTeaSelected();
		
		public void raiseEspressoSelected();
		
		public boolean isRaisedDoResetMoney();
		
		public boolean isRaisedDoResetMachine();
		
		public boolean isRaisedDoCleaning();
		
		public boolean isRaisedGrindBeans();
		
		public boolean isRaisedTakeTeaBag();
		
		public boolean isRaisedTakeOffTeaBag();
		
		public boolean isRaisedTakeCoffeePod();
		
		public boolean isRaisedHeatWater();
		
		public boolean isRaisedPutCup();
		
		public boolean isRaisedAddSugar();
		
		public boolean isRaisedPourWater();
		
		public boolean isRaisedPutBeans();
		
		public boolean isRaisedCheckPayment();
		
		public String getDrinkName();
		
		public void setDrinkName(String value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoResetMoneyRaised();
		public void onDoResetMachineRaised();
		public void onDoCleaningRaised();
		public void onGrindBeansRaised();
		public void onTakeTeaBagRaised();
		public void onTakeOffTeaBagRaised();
		public void onTakeCoffeePodRaised();
		public void onHeatWaterRaised();
		public void onPutCupRaised();
		public void onAddSugarRaised();
		public void onPourWaterRaised();
		public void onPutBeansRaised();
		public void onCheckPaymentRaised();
		}
	
	public SCInterface getSCInterface();
	
}
