/** Generated by YAKINDU Statechart Tools code generator. */
package drinkingfactory.drinkingfactory;

import drinkingfactory.IStatemachine;
import drinkingfactory.ITimerCallback;
import java.util.LinkedList;
import java.util.Queue;

public interface IDrinkingfactoryStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseDrinkSelected();
		
		public void raiseAddMoney();
		
		public void raisePaying();
		
		public void raisePaymentValidate();
		
		public void raiseResetMachine();
		
		public void raiseUserAction();
		
		public void raiseCupGrabbed();
		
		public void raiseHeatReached();
		
		public void raiseCupFilled();
		
		public boolean isRaisedDoResetMoney();
		
		public boolean isRaisedDoResetDrinkSetting();
		
		public boolean isRaisedDoResetMachine();
		
		public boolean isRaisedDoCleaning();
		
		public boolean isRaisedGrindBeans();
		
		public boolean isRaisedTakeTeaBag();
		
		public boolean isRaisedTakeOffTeaBag();
		
		public boolean isRaisedTakeCoffeePod();
		
		public boolean isRaisedHeatWater();
		
		public boolean isRaisedPutCup();
		
		public boolean isRaisedAddSugar();
		
		public boolean isRaisedPourWater();
		
		public boolean isRaisedGetDrink();
		
		public boolean isRaisedPutBeans();
		
		public long getDrinkNum();
		
		public void setDrinkNum(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
